
"""
    add_direction!(frames, name::Symbol, axes, direction3;
        direction6=nothing, direction9=nothing, direction12=nothing)

Add a new direction node to `frames`. The orientation of these direction depends only 
on time and is computed through the custom functions provided by the user. 

The input functions must accept only time as argument and their outputs must be as follows: 

- `direction3`: return a direction vector.
- `direction6`: return the direction and its first time derivative.
- `direction9`: return the direction and its first two time derivatives.
- `direction12`: return the direction and its first three time derivatives.

Missing derivative functions are computed via automatic differentiation.

Explicit cumulative-order functions take priority. Missing orders are generated by
differentiating the highest available lower-order representation.
"""
function add_direction!(
    frames::FrameSystem{O,N}, name::Symbol, axes, direction3;
    direction6=nothing, direction9=nothing, direction12=nothing,
) where {O,N}
    has_direction(frames, name) && throw(
        ArgumentError("direction with name=$name is already registered in the frame system.")
    )

    for (derivative_order, function_object) in enumerate(
        (direction6, direction9, direction12)
    )
        if O < derivative_order + 1 && !isnothing(function_object)
            @warn "ignoring $function_object, frame system order is less than $(derivative_order + 1)"
        end
    end

    functions = _translation_functions(
        Val(O), direction3, direction6, direction9, direction12)
    funs = DirectionFunctions{O,N}(functions...)

    axid = axes_id(frames, axes)
    has_axes(frames, axid) || throw(
        ArgumentError("Axes with ID $axid are not registered in the input frame system")
    )
    dir = DirectionDefinition{O,N}(name, length(directions(frames)) + 1, axid, funs)
    push!(directions(frames), Pair(name, dir))
    nothing
end
